print("WELCOME TO MY MADLIPS GAME")
print("follow the instructions to play the game")
print("fill in the gap to make a madlip")
name=input("ENTER A NAME: ")
verb=input('ENTER PAST TENSE OF RUN: ')
name2=input("ENTER ANOTHER NAME:")
verb2=input("ENTER THE PAST TENSE OF WIN: ")
print(f"{name} is very fast.")
print(f"he {verb} through the railway.")
print(f"before {name2} did.")